name = "bonjourr-services"
main = "src/index.ts"
compatibility_date = "2023-05-18"

[limits]
cpu_ms = 30

[dev]
ip = "127.0.0.1"
port = 8787

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1