name = "bonjourr-apis"
main = "src/index.ts"
compatibility_date = "2023-05-18"

[limits]
cpu_ms = 30

[env.ci]
command = "git submodule update --init --recursive" 

[dev]
ip = "127.0.0.1"
port = 8888

[observability]
enabled = true
head_sampling_rate = 0.1