name: CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            UNSPLASH: ${{ secrets.UNSPLASH }}
            WEATHER: ${{ secrets.WEATHER }}

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: latest

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Create .dev.vars file
              run: echo "UNSPLASH=${UNSPLASH}" > .dev.vars && echo "WEATHER=${WEATHER}" >> .dev.vars

            - name: Install dependencies
              run: pnpm install

            - name: Run tests
              run: pnpm test

    deploy:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Deploy
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_MAIN_ACCOUNT_ID }}
                  secrets: |
                      UNSPLASH
                      WEATHER
              env:
                  UNSPLASH: ${{ secrets.UNSPLASH }}
                  WEATHER: ${{ secrets.WEATHER }}
