name: CI/CD

on:
    workflow_run:
        workflows: ['Run tests']
        types:
            - completed

jobs:
    deploy:
        needs: run-tests
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Deploy
              uses: cloudflare/wrangler-action@v3.1.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_MAIN_ACCOUNT_ID }}
                  secrets: |
                      UNSPLASH
                      WEATHER
              env:
                  UNSPLASH: ${{ secrets.UNSPLASH }}
                  WEATHER: ${{ secrets.WEATHER }}
