name: Deploy

on:
    workflow_run:
        workflows: [Test]
        types: [completed]
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - uses: actions/checkout@v4

            - name: Init submodules
              run: git submodule update --init

            - name: Deploy Services
              uses: cloudflare/wrangler-action@v3
              with:
                  wranglerVersion: "4.30.0"
                  workingDirectory: "services"
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_MAIN_ACCOUNT_ID }}

            - name: Deploy Weather
              uses: cloudflare/wrangler-action@v3
              with:
                  wranglerVersion: "4.30.0"
                  workingDirectory: "weather"
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_MAIN_ACCOUNT_ID }}
