name: CI

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            UNSPLASH: ${{ secrets.UNSPLASH }}

        steps:
            - uses: actions/checkout@v3
            - uses: denoland/setup-deno@v2

            - name: Init submodules
              run: git submodule update --init

            - name: Create .dev.vars file
              run: echo "UNSPLASH=${UNSPLASH}" > ./services/.dev.vars

            - run: npx wrangler
            - run: nohup npx wrangler dev --cwd services & sleep 3 && deno task test:services
            - run: nohup npx wrangler dev --cwd weather & sleep 3 && deno task test:weather

    deploy:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Init submodules
              run: git submodule update --init

            - name: Deploy Services
              uses: cloudflare/wrangler-action@v3
              with:
                  wranglerVersion: "4.30.0"
                  workingDirectory: "services"
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_MAIN_ACCOUNT_ID }}

            - name: Deploy Weather
              uses: cloudflare/wrangler-action@v3
              with:
                  wranglerVersion: "4.30.0"
                  workingDirectory: "weather"
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_MAIN_ACCOUNT_ID }}
