name: CI

on:
    push:
        branches:
            - split-workers

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            UNSPLASH: ${{ secrets.UNSPLASH }}

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: latest
                  cache: 'pnpm'

            - name: Init submodules
              run: git submodule update --init

            - name: Install dependencies
              run: pnpm i -r

            - name: API - Create .dev.vars file
              run: echo "UNSPLASH=${UNSPLASH}" > ./api/.dev.vars

            - name: Run tests
              run: pnpm run test

    deploy:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Init submodules
              run: git submodule update --init

            - name: Deploy API
              uses: cloudflare/wrangler-action@v3
              with:
                  workingDirectory: 'api'
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_MAIN_ACCOUNT_ID }}

            - name: Deploy Weather
              uses: cloudflare/wrangler-action@v3
              with:
                  workingDirectory: 'weather'
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_MAIN_ACCOUNT_ID }}
