name: Update Submodules

on:
    repository_dispatch:
        types: [update]

jobs:
    update_submodules:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Update submodules
              run: |
                  git submodule update --init --recursive
                  git submodule update --remote --recursive

            - uses: EndBug/add-and-commit@v9
              with:
                  message: 'Updated submodules'
