name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy-main-account:
    runs-on: ubuntu-latest
    name: To main account
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.1.0     
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_MAIN_ACCOUNT_ID }}
          secrets: |
            UNSPLASH
            WEATHER
        env:
          UNSPLASH: ${{ secrets.UNSPLASH }}
          WEATHER: ${{ secrets.WEATHER }}

  deploy-first-fallback-account:
    runs-on: ubuntu-latest
    name: To first fallback
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.1.0     
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_FALLBACK_1_ACCOUNT_ID }}
          secrets: |
            UNSPLASH
            WEATHER
        env:
          UNSPLASH: ${{ secrets.UNSPLASH }}
          WEATHER: ${{ secrets.WEATHER }}
          

  deploy-third-account:
    runs-on: ubuntu-latest
    name: To second fallback
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.1.0     
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_FALLBACK_2_ACCOUNT_ID }}
          secrets: |
            UNSPLASH
            WEATHER
        env:
          UNSPLASH: ${{ secrets.UNSPLASH }}
          WEATHER: ${{ secrets.WEATHER }}