name: CI/CD

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    run-tests:
        runs-on: ubuntu-latest

        env:
            UNSPLASH: ${{ secrets.UNSPLASH }}
            WEATHER: ${{ secrets.WEATHER }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install wrangler globally
              run: npm install --global wrangler

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

    # deploy-main-account:
    #     needs: run-tests
    #     runs-on: ubuntu-latest
    #     if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v3

    #         - name: Deploy
    #           uses: cloudflare/wrangler-action@v3.1.0
    #           with:
    #               apiToken: ${{ secrets.CF_API_TOKEN }}
    #               accountId: ${{ secrets.CF_MAIN_ACCOUNT_ID }}
    #               secrets: |
    #                   UNSPLASH
    #                   WEATHER
    #           env:
    #               UNSPLASH: ${{ secrets.UNSPLASH }}
    #               WEATHER: ${{ secrets.WEATHER }}
